### ISSUE TITLE
Is it possible to disable (or use another function) stringify-value

### ISSUE THREAD

**Issue by juergenhoetzel** [kumarshantanu/cambium#2]
I use this *Graylog* appender: https://github.com/osiegmar/logback-gelf

When logging: 

```clojure
(ns gelftest.core
  (:require [cambium.core :as clog]))
  (clog/info {:key 1} "Foo Bar")
```

this results in the following Graylog/Elasticsearch type mapping:
```json
{"key":{"type":"string","index":"not_analyzed"}}
```
is it possible to disable the stringification?

Thanks for this nice library :+1:

**Comment by kumarshantanu** [comment]
You are probably using one of the provided codecs. Please refer https://github.com/kumarshantanu/cambium#what-is-a-cambium-codec - you can provide your own codec. For non-simplistic cases, you may also need to provide a custom Logback (or Log4j2) layout.

I would be happy to look into your use-case if you can share more details, e.g. your sample `logback.xml` file. In case you need to share the config privately, please feel free to email me at the address mention in the README. The thing I am interested in knowing is whether you are using `de.siegmar.logbackgelf.GelfLayout` or any other layout, and the parameters passed to it.

**Comment by kumarshantanu** [comment]
Looks like the Graylog layout emits JSON string. Can you try if the following works for you?

1. Replace dependency `[cambium/cambium.codec-simple "0.9.0"]` with `[cambium/cambium.codec-cheshire "0.9.0"]` in `project.clj` so that the codec can marshall and unmarshall using JSON string.
2. Add dependency `[logback-bundle/json-bundle "0.3.0"]` in `project.clj`.
3. Configure the Logback `layout` as shown here: https://github.com/kumarshantanu/logback-bundle#quickstart-json-logging but replace `ch.qos.logback.contrib.json.classic.JsonLayout` with `logback_bundle.json.FlatJsonLayout`. (Only configure the layout, leaving the appender intact.)
4. At the beginning of your application execute the following:
```clojure
(require '[cambium.codec :as codec])
(require '[logback-bundle.json.flat-layout :as flat])
(flat/set-decoder! codec/destringify-val)
```

**Comment by juergenhoetzel** [comment]
Thanks for all your feedback! Very useful to get an insight into this nice project.

> Add dependency [logback-bundle/json-bundle "0.3.0"] in project.clj.

This results in

```
Reported exception:
java.lang.NoSuchMethodError: ch.qos.logback.core.util.Loader.getResourceOccurrenceCount(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/util/Set;
	at ch.qos.logback.classic.util.ContextInitializer.multiplicityWarning(ContextInitializer.java:173)
	at ch.qos.logback.classic.util.ContextInitializer.statusOnResourceSearch(ContextInitializer.java:196)
	at ch.qos.logback.classic.util.ContextInitializer.getResource(ContextInitializer.java:143)
	at ch.qos.logback.classic.util.ContextInitializer.findURLOfDefaultConfigurationFile(ContextInitializer.java:137)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at clojure.tools.logging$eval433$reify__434.get_logger(logging.clj:288)
	at gelftest.core$eval11907.invokeStatic(form-init8907550923655766556.clj:13)
	at gelftest.core$eval11907.invoke(form-init8907550923655766556.clj:13)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
	at clojure.main$repl$fn__7417.invoke(main.clj:258)
	at clojure.main$repl.invokeStatic(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:174)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__945.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__990$fn__993.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__985.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

I use this *project.clj*:

```clojure
(defproject gelftest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/tools.logging "0.3.1"]
                 [cambium/cambium.core "0.9.0"]
                 [logback-bundle/json-bundle "0.3.0"] 
                 [cambium/cambium.codec-cheshire "0.9.0"]  ; nesting-capable codec
                 [de.siegmar/logback-gelf "1.0.4"]])


```

And this *logback.xml*:

```xml
<configuration debug="true">
    <appender name="GELF" class="de.siegmar.logbackgelf.GelfTcpAppender">
        <graylogHost>pidsley</graylogHost>
        <graylogPort>12201</graylogPort>
    </appender>
    <root level="debug">
        <appender-ref ref="GELF" />
    </root>
</configuration>

```

> https://github.com/kumarshantanu/cambium#what-is-a-cambium-codec - you can provide your own codec. 

BTW: It would be nice to configure the *codec* at runtime (maybe via a *codec* *protocol*) instead of hardcoding *cambium.codec*?

**Comment by kumarshantanu** [comment]
I am able to reproduce the error, which appears to be occurring due to conflicting Logback-clasic version. The issue went away when I tried the following dependency spec:

`[de.siegmar/logback-gelf "1.0.4" :exclusions [ch.qos.logback/logback-classic]]`

The codec is currently hard-coded so that somebody can direct-link the fns into static methods for best performance. The codec fns are called by macros and logging initialization is sadly a bit tricky. A protocol would lead to a virtual call (in theory slower than static), but I have that in my mind for future consideration. Thanks for the suggestion. :)

**Comment by juergenhoetzel** [comment]
> I am able to reproduce the error, which appears to be occurring due to conflicting Logback-clasic version. The issue went away when I tried the following dependency spec:
> 
> [de.siegmar/logback-gelf "1.0.4" :exclusions [ch.qos.logback/logback-classic]]
>
Thanks! But the *int* is still encoded as *string*. Sending

```clojure
(clog/info {:key 1} "Foo Bar")
```
results in this *JSON* on the wire (using *sudo tcpdump -l -w - port 12201 | tcpflow -C -r -*)

```json
{"version":"1.1","host":"samson.fritz.box","short_message":"Foo Bar","full_message":"Foo Bar\n","timestamp":1495316970.664,"level":6,"_thread_name":"nREPL-worker-6","_logger_name":"gelftest.core","_key":"1"}

``` 

> The codec is currently hard-coded so that somebody can direct-link the fns into static methods for best performance. The codec fns are called by macros and logging initialization is sadly a bit tricky. A protocol would lead to a virtual call (in theory slower than static), but I have that in my mind for future consideration. Thanks for the suggestion. :)

I see. But i suspect the overhead of a virtual call is negligiblecompared  to the time consumed by the actual logging IO.

Thanks again for your helpful feedback. :+1:

**Comment by kumarshantanu** [comment]
I think the _int_ is still encoded as _string_ because you are not using `FlatJsonLayout` yet. SLF4J strictly supports only `Map<String, String>` so we need to encode at Cambium end and decode in the layout to preserve types and nesting. I tried configuring `GelfTcpAppender` with `FlatJsonLayout` but it expects only `GelfLayout`. Also tried another logback/gelf library to no avail. Looks like currently, the sidecar http://docs.graylog.org/en/2.2/pages/collector_sidecar.html may be useful as a fallback option. If you use the sidecar approach, you can emit the logs as JSON file and have the sidecar ship it.

I am interested in getting proper Graylog support for Cambium, but that probably entails writing (or locating) an appender that is compatible with Logback's official contrib `JsonLayout` on which `FlatJsonLayout` is based. Another alternative would be to use a RabbitMQ appender with Graylog AMQP (I can quickly put together one that already works with Logstash - please let me know.)

On the codec-protocol thing: I think you are right about logging overhead being larger than a static/virtual call difference. I still need to find a good way to make the protocol implementation configurable because it cannot be passed as an argument to every logging call, and putting it behind a `volatile` may impact cache coherency. Given that both Logback and Log4j2 support asynchronous appenders/wrappers, the actual heavy lifting is pushed away to threads other than the ones using Cambium.

**Comment by juergenhoetzel** [comment]
> I am interested in getting proper Graylog support for Cambium, but that probably entails writing (or locating) an appender that is compatible with Logback's official contrib JsonLayout on which FlatJsonLayout is based. 

*Cambium* works fine for me wirh Graylog. It's just the type mapping. And as you described its  actually not an *Cambium* issue but an issue of the Java logging frameworks.

> Another alternative would be to use a RabbitMQ appender with Graylog AMQP (I can quickly put together one that already works with Logstash - please let me know.)

I came up with a rather simple solution using [Graylog functions](http://docs.graylog.org/en/2.2/pages/pipelines/functions.html):

```python
rule "enforce_system_id_long"
when 
   has_field("remote_system_id")
then
   let fixed_id = to_long($message.remote_system_id);
   set_field("remote_system_id", fixed_id);
end  
```

Thanks for your valuable feedback and making logging in *clojure* idiomatic :+1:
